---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: graphql
  name: graphql
spec:
  replicas: 1
  selector:
    app: graphql
    deploymentconfig: graphql
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: graphql
        deploymentconfig: graphql
    spec:
      containers:
        - image: quay.io/xphyr/graphql:v2
          imagePullPolicy: Always
          name: graphql
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  name: graphql      
spec:
  selector:                  
    app: graphql
  ports:
  - name: graphql-webport
    port: 4000              
    protocol: TCP
    targetPort: 4000